types: add typings for unist util filter
syntax-tree/unist-util-filter pull request #2
Opened 2019-10-26 19:59 UTC by ChristianMurphy

/cc @Rokt33r

2019-10-26 20:08 UTC, wooorm approved these changes

2019-10-28 03:27 UTC, Rokt33r requested changes

2019-10-28 03:27 UTC, Rokt33r commented on types/unist-util-filter-tests.ts
> +filter({type: 'root'}, {cascade: false}, 'root') // $ExpectType Node | null
Duplicated

2019-10-28 04:33 UTC, ChristianMurphy commented on types/unist-util-filter-tests.ts
> +filter({type: 'root'}, {cascade: false}, 'root') // $ExpectType Node | null
good catch, removed

2019-10-28 08:03 UTC, merged